name: Update Os List on New Release

on:
  repository_dispatch:
    types:
      - new-release
  workflow_dispatch:

jobs:
  generate-os-list-and-create-pr:
    name: Generate OS List JSON file and create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./utils/os-list-generator
        run: npm install

      - name: Run script to generate JSON file
        working-directory: ./utils/os-list-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js

      - name: Run script to generate PR
        working-directory: ./utils/os-list-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node create-pr.js